/*
 * This source file was generated by the Gradle 'init' task
 */
package com.krispachi.KasirTokoKomik;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
        // Blok kode untuk mengatur Look and Feel
        FlatLightLaf.setup();
        
        // Menampilkan GUI Login
        SwingUtilities.invokeLater(() -> {
            Login form = new Login();
            form.setVisible(true);
        });
    }
}
